# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 70, 60, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 121, 91))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 121, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuTesting = QtWidgets.QMenu(self.menubar)
        self.menuTesting.setObjectName("menuTesting")
        self.menuExperiments = QtWidgets.QMenu(self.menubar)
        self.menuExperiments.setObjectName("menuExperiments")
        self.menuHMRE = QtWidgets.QMenu(self.menubar)
        self.menuHMRE.setObjectName("menuHMRE")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSound_Video = QtWidgets.QAction(MainWindow)
        self.actionSound_Video.setCheckable(True)
        self.actionSound_Video.setObjectName("actionSound_Video")
        self.actionDouble_Choice = QtWidgets.QAction(MainWindow)
        self.actionDouble_Choice.setCheckable(True)
        self.actionDouble_Choice.setObjectName("actionDouble_Choice")
        self.actionFour_Direction = QtWidgets.QAction(MainWindow)
        self.actionFour_Direction.setCheckable(True)
        self.actionFour_Direction.setObjectName("actionFour_Direction")
        self.actionMonitor = QtWidgets.QAction(MainWindow)
        self.actionMonitor.setCheckable(True)
        self.actionMonitor.setObjectName("actionMonitor")
        self.actionTest_Vector_Conversions_Math = QtWidgets.QAction(MainWindow)
        self.actionTest_Vector_Conversions_Math.setCheckable(True)
        self.actionTest_Vector_Conversions_Math.setObjectName("actionTest_Vector_Conversions_Math")
        self.actionTest_Video_Player = QtWidgets.QAction(MainWindow)
        self.actionTest_Video_Player.setCheckable(True)
        self.actionTest_Video_Player.setObjectName("actionTest_Video_Player")
        self.actionTest_Continuous_Fluxgate_Monitor = QtWidgets.QAction(MainWindow)
        self.actionTest_Continuous_Fluxgate_Monitor.setCheckable(True)
        self.actionTest_Continuous_Fluxgate_Monitor.setObjectName("actionTest_Continuous_Fluxgate_Monitor")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setCheckable(True)
        self.actionOutput.setObjectName("actionOutput")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setCheckable(True)
        self.actionClose.setObjectName("actionClose")
        self.actionCalibrate_Zero_Magnetic_Field = QtWidgets.QAction(MainWindow)
        self.actionCalibrate_Zero_Magnetic_Field.setCheckable(True)
        self.actionCalibrate_Zero_Magnetic_Field.setObjectName("actionCalibrate_Zero_Magnetic_Field")
        self.actionCalibrate_Magnetic_Field_Intensity = QtWidgets.QAction(MainWindow)
        self.actionCalibrate_Magnetic_Field_Intensity.setCheckable(True)
        self.actionCalibrate_Magnetic_Field_Intensity.setObjectName("actionCalibrate_Magnetic_Field_Intensity")
        self.actionFluxgate_Continuous_Monitor_Window = QtWidgets.QAction(MainWindow)
        self.actionFluxgate_Continuous_Monitor_Window.setCheckable(True)
        self.actionFluxgate_Continuous_Monitor_Window.setObjectName("actionFluxgate_Continuous_Monitor_Window")
        self.actionRF_Waveform_Generator_Control = QtWidgets.QAction(MainWindow)
        self.actionRF_Waveform_Generator_Control.setCheckable(True)
        self.actionRF_Waveform_Generator_Control.setObjectName("actionRF_Waveform_Generator_Control")
        self.actionSettings_Manager = QtWidgets.QAction(MainWindow)
        self.actionSettings_Manager.setCheckable(True)
        self.actionSettings_Manager.setObjectName("actionSettings_Manager")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        self.actionCascade.setCheckable(True)
        self.actionCascade.setObjectName("actionCascade")
        self.actionTile_Vertical = QtWidgets.QAction(MainWindow)
        self.actionTile_Vertical.setCheckable(True)
        self.actionTile_Vertical.setObjectName("actionTile_Vertical")
        self.actionTile_Horizontal = QtWidgets.QAction(MainWindow)
        self.actionTile_Horizontal.setCheckable(True)
        self.actionTile_Horizontal.setObjectName("actionTile_Horizontal")
        self.action1_Sound_Video = QtWidgets.QAction(MainWindow)
        self.action1_Sound_Video.setCheckable(True)
        self.action1_Sound_Video.setChecked(True)
        self.action1_Sound_Video.setObjectName("action1_Sound_Video")
        self.actionSystem_Status = QtWidgets.QAction(MainWindow)
        self.actionSystem_Status.setCheckable(True)
        self.actionSystem_Status.setObjectName("actionSystem_Status")
        self.menuTesting.addAction(self.actionOutput)
        self.menuTesting.addAction(self.actionMonitor)
        self.menuTesting.addAction(self.actionSound_Video)
        self.menuTesting.addAction(self.actionTest_Vector_Conversions_Math)
        self.menuTesting.addAction(self.actionTest_Video_Player)
        self.menuTesting.addAction(self.actionTest_Continuous_Fluxgate_Monitor)
        self.menuExperiments.addAction(self.actionDouble_Choice)
        self.menuExperiments.addAction(self.actionFour_Direction)
        self.menuHMRE.addAction(self.actionSystem_Status)
        self.menuHMRE.addSeparator()
        self.menuHMRE.addAction(self.actionClose)
        self.menuTools.addAction(self.actionCalibrate_Zero_Magnetic_Field)
        self.menuTools.addAction(self.actionCalibrate_Magnetic_Field_Intensity)
        self.menuTools.addAction(self.actionFluxgate_Continuous_Monitor_Window)
        self.menuTools.addAction(self.actionRF_Waveform_Generator_Control)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addAction(self.actionTile_Vertical)
        self.menuWindow.addAction(self.actionTile_Horizontal)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.action1_Sound_Video)
        self.menuSettings.addAction(self.actionSettings_Manager)
        self.menubar.addAction(self.menuHMRE.menuAction())
        self.menubar.addAction(self.menuTesting.menuAction())
        self.menubar.addAction(self.menuExperiments.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.actionClose.changed.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Human Magnetic Reception Experiment"))
        self.groupBox.setTitle(_translate("MainWindow", "System Status"))
        self.label_4.setText(_translate("MainWindow", "Audio/Video:"))
        self.label_3.setText(_translate("MainWindow", "Daq:"))
        self.label_5.setText(_translate("MainWindow", "Push button:"))
        self.label_2.setText(_translate("MainWindow", "Off"))
        self.label_10.setText(_translate("MainWindow", "Off"))
        self.label_11.setText(_translate("MainWindow", "Off"))
        self.menuTesting.setTitle(_translate("MainWindow", "Testing"))
        self.menuExperiments.setTitle(_translate("MainWindow", "Experiments"))
        self.menuHMRE.setTitle(_translate("MainWindow", "HMRE"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionSound_Video.setText(_translate("MainWindow", "Sound/Video"))
        self.actionDouble_Choice.setText(_translate("MainWindow", "Double Choice"))
        self.actionFour_Direction.setText(_translate("MainWindow", "Four Direction"))
        self.actionMonitor.setText(_translate("MainWindow", "Monitor"))
        self.actionTest_Vector_Conversions_Math.setText(_translate("MainWindow", "Test Vector Conversions / Math"))
        self.actionTest_Video_Player.setText(_translate("MainWindow", "Test Video Player"))
        self.actionTest_Continuous_Fluxgate_Monitor.setText(_translate("MainWindow", "Test Continuous Fluxgate Monitor"))
        self.actionOutput.setText(_translate("MainWindow", "Output"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionCalibrate_Zero_Magnetic_Field.setText(_translate("MainWindow", "Calibrate Zero Magnetic Field"))
        self.actionCalibrate_Magnetic_Field_Intensity.setText(_translate("MainWindow", "Calibrate Magnetic Field Intensity"))
        self.actionFluxgate_Continuous_Monitor_Window.setText(_translate("MainWindow", "Fluxgate Continuous Monitor Window"))
        self.actionRF_Waveform_Generator_Control.setText(_translate("MainWindow", "RF Waveform Generator Control"))
        self.actionSettings_Manager.setText(_translate("MainWindow", "Settings Manager"))
        self.actionCascade.setText(_translate("MainWindow", "Cascade"))
        self.actionTile_Vertical.setText(_translate("MainWindow", "Tile Vertical"))
        self.actionTile_Horizontal.setText(_translate("MainWindow", "Tile Horizontal"))
        self.action1_Sound_Video.setText(_translate("MainWindow", "1 Sound & Video"))
        self.action1_Sound_Video.setToolTip(_translate("MainWindow", "1 Sound & Video"))
        self.actionSystem_Status.setText(_translate("MainWindow", "System Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

